@piscologos = http://localhost:3000/psicologos 
@citas = http://localhost:3000/citas

@pacientes = http://localhost:3000/pacientes


###
GET {{piscologos}}/25

###
POST {{piscologos}}
Content-Type: application/json

{
    "nombre": "otro juan",
    "apellido": "González",
    "especialidad": "Psicología Clínica",
    "correo_electronico": "maria.gonzalez@example.com",
    "telefono": "555-1234",
    "usuario": "mariag",
    "contrasena": "segura123"
}

###
DELETE {{piscologos}}/24

###
PUT {{piscologos}}/25
Content-Type: application/json

{
    "nombre": "junior ",
    "apellido": "h"
}

###
GET {{citas}}

###
GET {{citas}}/1

###
POST {{citas}}
Content-Type: application/json

{
    "id_psicologo": 1,
    "id_paciente": 2,
    "fecha_cita": "2024-08-30",
    "hora_cita": "15:00:00",
    "tipo_cita": "Consulta",
    "estado": "Confirmada"
}

###
DELETE {{citas}}/12

###
PUT {{citas}}/14
Content-Type: application/json

{
    "tipo_cita": "cita actualizada"
}

GET {{pacientes}}

###
POST {{pacientes}}
Content-Type: application/json

{
  "nombre": "Juana",
  "apellido": "Pereza",
  "fecha_nacimiento": "1990-02-01",
  "correo_electronico": "juanapereza@example.com",
  "telefono": "123456",
  "direccion": "Calle 12s3",
  "id_psicologo": 2,
  "usuario": "juanapereza",
  "contrasena": "1234562",
  "tarifa": 100,
  "nombre_emergencia": "Mariana",
  "contacto_emergencia": "815654321",
  "estado_civil": "Soltero",
  "ocupacion": "Estudiante",
  "fecha_registro": "2021-04-01"
}

###
DELETE {{pacientes}}/9