@piscologos = http://localhost:3000/psicologos 
@citas = http://localhost:3000/citas
@pacientes = http://localhost:3000/pacientes
@diagnosticos = http://localhost:3000/diagnosticos
@notas = http://localhost:3000/notas

###
GET {{piscologos}}

###
GET {{piscologos}}/27

###
POST {{piscologos}}
Content-Type: application/json

{
    "nombre": "Adrina",
    "apellido": "Arreola",
    "especialidad": "Logoterapia",
    "correo_electronico": "Aun no lo sabemos jaja",
    "telefono": "6181744287",
    "usuario": "adri",
    "contrasena": "12345"
}

###
DELETE {{piscologos}}/24

###
PUT {{piscologos}}/27
Content-Type: application/json

{
    "rol": "psicologo"
}

###
GET {{citas}}

###
GET {{citas}}/1

###
POST {{citas}}
Content-Type: application/json

{
    "id_psicologo": 1,
    "id_paciente": 2,
    "fecha_cita": "2024-08-30",
    "hora_cita": "15:00:00",
    "tipo_cita": "Consulta",
    "estado": "Cancelada"
}

###
DELETE {{citas}}/15

###
PUT {{citas}}/14
Content-Type: application/json

{
    "fecha_cita": "2024-09-17"
}

###
GET {{pacientes}}

###
GET {{pacientes}}/1

###
POST {{pacientes}}
Content-Type: application/json

{
  "nombre": "Luna",
  "apellido": "Martinez",
  "fecha_nacimiento": "1990-02-01",
  "correo_electronico": "lunamartinez@example.com",
  "telefono": "123456133",
  "direccion": "Calle 12s35",
  "id_psicologo": 8,
  "usuario": "lunalatuna",
  "contrasena": "1234567",
  "tarifa": 100,
  "nombre_emergencia": "Luis Daniel",
  "contacto_emergencia": "8156558321",
  "estado_civil": "Casada",
  "ocupacion": "Estudiante",
  "fecha_registro": "2024-04-01"
}

###
DELETE {{pacientes}}/8

###
PUT {{pacientes}}/3
Content-Type: application/json

{
  "id_psicologo": 27
}

###
GET {{diagnosticos}}

###
GET {{diagnosticos}}/1

###
POST {{diagnosticos}}
Content-Type: application/json

{
  "id_paciente": 5,
  "id_psicologo": 25,
  "fecha_diagnostico": "2024-09-08",
  "diagnostico": "Depresion por desamor8("
}

###
DELETE {{diagnosticos}}/7

###
PUT {{diagnosticos}}/8
Content-Type: application/json

{
  "diagnostico": "Ansiedad por examenes"
}

###
GET {{notas}}

###
GET {{notas}}/2

###
POST {{notas}}
Content-Type: application/json

{
  "propuesta_terap": "Para la siguiente sesion se propone: enseñanza de ejercicios de respiración"
}

###
DELETE {{notas}}/5

###
PUT {{notas}}/1
Content-Type: application/json

{
  "propuesta_terap": "prueba de actualizacion3"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
  "usuario": "adri",
  "contrasena": "12345"
}

###
GET http://localhost:3000/citas/paciente/1



